/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PostsResponse } from './PostsResponse.ts'

export type GetPostsQueryParams = {
  /**
   * @type integer, int32
   */
  page: number
  /**
   * @type integer, int32
   */
  pageSize: number
}

/**
 * @description OK
 */
export type GetPosts200 = PostsResponse

export type GetPostsQueryResponse = GetPosts200

export type GetPostsQuery = {
  Response: GetPosts200
  QueryParams: GetPostsQueryParams
  Errors: any
}