/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Post } from './Post.ts'

export type PostsResponse = {
  /**
   * @type array
   */
  data: Post[]
  /**
   * @type integer, int32
   */
  nextPage: number | null
}