export type { GetPostsQueryKey } from './useGetPosts.ts'
export type { GetPostsInfiniteQueryKey } from './useGetPostsInfinite.ts'
export type { GetPostsSuspenseQueryKey } from './useGetPostsSuspense.ts'
export { getPostsQueryKey, getPosts, getPostsQueryOptions, useGetPosts } from './useGetPosts.ts'
export { getPostsInfiniteQueryKey, getPostsInfinite, getPostsInfiniteQueryOptions, useGetPostsInfinite } from './useGetPostsInfinite.ts'
export { getPostsSuspenseQueryKey, getPostsSuspense, getPostsSuspenseQueryOptions, useGetPostsSuspense } from './useGetPostsSuspense.ts'