/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { GetPostsQueryResponse, GetPostsQueryParams } from '../types/GetPosts.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getPostsQueryKey = (params: GetPostsQueryParams) => [{ url: '/posts' }, ...(params ? [params] : [])] as const

export type GetPostsQueryKey = ReturnType<typeof getPostsQueryKey>

/**
 * @description Gets a list of posts with Seth
 * {@link /posts}
 */
export async function getPosts(params: GetPostsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetPostsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/posts`,
    baseURL: 'http://localhost:3000',
    params,
    ...requestConfig,
  })
  return res.data
}

export function getPostsQueryOptions(params: GetPostsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPostsQueryKey(params)
  return queryOptions<GetPostsQueryResponse, ResponseErrorConfig<Error>, GetPostsQueryResponse, typeof queryKey>({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getPosts(params, config)
    },
  })
}

/**
 * @description Gets a list of posts with Seth
 * {@link /posts}
 */
export function useGetPosts<TData = GetPostsQueryResponse, TQueryData = GetPostsQueryResponse, TQueryKey extends QueryKey = GetPostsQueryKey>(
  params: GetPostsQueryParams,
  options: {
    query?: Partial<QueryObserverOptions<GetPostsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getPostsQueryKey(params)

  const query = useQuery(
    {
      ...(getPostsQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}