/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { GetPostsQueryResponse, GetPostsQueryParams } from '../types/GetPosts.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getPostsSuspenseQueryKey = (params: GetPostsQueryParams) => [{ url: '/posts' }, ...(params ? [params] : [])] as const

export type GetPostsSuspenseQueryKey = ReturnType<typeof getPostsSuspenseQueryKey>

/**
 * @description Gets a list of posts
 * {@link /posts}
 */
export async function getPostsSuspense(params: GetPostsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetPostsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/posts`,
    baseURL: 'http://localhost:3000',
    params,
    ...requestConfig,
  })
  return res.data
}

export function getPostsSuspenseQueryOptions(params: GetPostsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPostsSuspenseQueryKey(params)
  return queryOptions<GetPostsQueryResponse, ResponseErrorConfig<Error>, GetPostsQueryResponse, typeof queryKey>({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getPostsSuspense(params, config)
    },
  })
}

/**
 * @description Gets a list of posts
 * {@link /posts}
 */
export function useGetPostsSuspense<TData = GetPostsQueryResponse, TQueryKey extends QueryKey = GetPostsSuspenseQueryKey>(
  params: GetPostsQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<GetPostsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getPostsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getPostsSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}