export type { PostsQueryKey } from './usePosts.ts'
export type { PostsInfiniteQueryKey } from './usePostsInfinite.ts'
export type { PostsSuspenseQueryKey } from './usePostsSuspense.ts'
export { postsQueryKey, posts, postsQueryOptions, usePosts } from './usePosts.ts'
export { postsInfiniteQueryKey, postsInfinite, postsInfiniteQueryOptions, usePostsInfinite } from './usePostsInfinite.ts'
export { postsSuspenseQueryKey, postsSuspense, postsSuspenseQueryOptions, usePostsSuspense } from './usePostsSuspense.ts'