/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { PostsQueryResponse } from '../types/Posts.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const postsQueryKey = () => [{ url: '/' }] as const

export type PostsQueryKey = ReturnType<typeof postsQueryKey>

/**
 * {@link /}
 */
export async function posts(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<PostsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/`,
    baseURL: 'http://localhost:3000',
    ...requestConfig,
  })
  return res.data
}

export function postsQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = postsQueryKey()
  return queryOptions<PostsQueryResponse, ResponseErrorConfig<Error>, PostsQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return posts(config)
    },
  })
}

/**
 * {@link /}
 */
export function usePosts<TData = PostsQueryResponse, TQueryData = PostsQueryResponse, TQueryKey extends QueryKey = PostsQueryKey>(
  options: {
    query?: Partial<QueryObserverOptions<PostsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? postsQueryKey()

  const query = useQuery(
    {
      ...(postsQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}