/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { PostsQueryResponse } from '../types/Posts.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const postsSuspenseQueryKey = () => [{ url: '/' }] as const

export type PostsSuspenseQueryKey = ReturnType<typeof postsSuspenseQueryKey>

/**
 * {@link /}
 */
export async function postsSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<PostsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/`,
    baseURL: 'http://localhost:3000',
    ...requestConfig,
  })
  return res.data
}

export function postsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = postsSuspenseQueryKey()
  return queryOptions<PostsQueryResponse, ResponseErrorConfig<Error>, PostsQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return postsSuspense(config)
    },
  })
}

/**
 * {@link /}
 */
export function usePostsSuspense<TData = PostsQueryResponse, TQueryKey extends QueryKey = PostsSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<PostsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? postsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(postsSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}