/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { PostsQueryResponse } from '../types/Posts.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const postsInfiniteQueryKey = () => [{ url: '/' }] as const

export type PostsInfiniteQueryKey = ReturnType<typeof postsInfiniteQueryKey>

/**
 * {@link /}
 */
export async function postsInfinite(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<PostsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/`,
    baseURL: 'http://localhost:3000',
    ...requestConfig,
  })
  return res.data
}

export function postsInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = postsInfiniteQueryKey()
  return infiniteQueryOptions<PostsQueryResponse, ResponseErrorConfig<Error>, PostsQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return postsInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextPage'],
    getPreviousPageParam: (firstPage) => firstPage['nextPage'],
  })
}

/**
 * {@link /}
 */
export function usePostsInfinite<TData = InfiniteData<PostsQueryResponse>, TQueryData = PostsQueryResponse, TQueryKey extends QueryKey = PostsInfiniteQueryKey>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<PostsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? postsInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(postsInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}