/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PostsListingDto } from './PostsListingDto.ts'

export type Posts200 = PostsListingDto

export type PostsQueryResponse = Posts200

export type PostsQuery = {
  Response: Posts200
  Errors: any
}