/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostDto = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  title: string
  /**
   * @type string
   */
  content: string
}