/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PostDto } from './PostDto.ts'

export type PostsListingDto = {
  /**
   * @type array
   */
  data: PostDto[]
  /**
   * @type number
   */
  nextPage: number | null
}